"""initial snapshot schema

Baseline migration. It materialises the entire model metadata so the migration can
never drift from ``db/models.py``. Subsequent migrations use explicit ``op`` calls
(autogenerated) to alter this baseline.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-13
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from sift.db.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
