"""add movies.cutoff_unmet

Adds the deterministic upgrade-detector flag (current file below Radarr's profile
cutoff). Explicit ``op`` calls, per the convention that everything after the
baseline is an incremental, autogenerated-style migration.

Revision ID: 0002_movie_cutoff_unmet
Revises: 0001_initial
Create Date: 2026-07-13
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_movie_cutoff_unmet"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _has(bind: sa.engine.Connection, column: str) -> bool:
    return column in {c["name"] for c in sa.inspect(bind).get_columns("movies")}


def _has_index(bind: sa.engine.Connection, name: str) -> bool:
    return name in {i["name"] for i in sa.inspect(bind).get_indexes("movies")}


def upgrade() -> None:
    # The 0001 baseline materialises the *current* model via create_all, so on a fresh
    # chain it already includes this column. Guard the add so `upgrade head` is safe
    # both from a legacy pre-column DB and from a create_all baseline.
    bind = op.get_bind()
    if not _has(bind, "cutoff_unmet"):
        op.add_column(
            "movies",
            sa.Column("cutoff_unmet", sa.Boolean(), nullable=False, server_default=sa.false()),
        )
    if not _has_index(bind, "ix_movies_cutoff_unmet"):
        op.create_index("ix_movies_cutoff_unmet", "movies", ["cutoff_unmet"])


def downgrade() -> None:
    bind = op.get_bind()
    if _has_index(bind, "ix_movies_cutoff_unmet"):
        op.drop_index("ix_movies_cutoff_unmet", table_name="movies")
    if _has(bind, "cutoff_unmet"):
        op.drop_column("movies", "cutoff_unmet")
